{
 "title": "Coffee Factory",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Color Tracker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_user_beanColor",
     "legendFormat": "Color Tracker (Volts DC)"
    }
   ]
  },
  {
   "title": "Current Bean Color",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sag_apama_correlator_user_beanIllustrator"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_user_drum",
     "legendFormat": "Roast Drum Temperature (Celsius)"
    },
    {
     "expr": "sag_apama_correlator_user_extractorTemp",
     "legendFormat": "Extractor Drum Temperature (Celsius)"
    },
    {
     "expr": "sag_apama_correlator_user_freezerDryerTemp",
     "legendFormat": "Tube Temperature (Celsius)"
    }
   ]
  },
  {
   "title": "Extraction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_user_caffeine",
     "legendFormat": "Caffeine (units)"
    },
    {
     "expr": "sag_apama_correlator_user_volatileOils",
     "legendFormat": "VolatileOils (units)"
    },
    {
     "expr": "sag_apama_correlator_user_organicAcids",
     "legendFormat": "Organic Acids (units)"
    }
   ]
  },
  {
   "title": "Sublimation Tube",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_user_moisture",
     "legendFormat": "Moisture"
    },
    {
     "expr": "sag_apama_correlator_user_vacuum",
     "legendFormat": "Vacuum Pressure (mTorr)"
    }
   ]
  },
  {
   "title": "Freezer Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 17 },
   "targets": [
    {
     "expr": "sag_apama_correlator_user_freezerTemp",
     "legendFormat": "Freezer Temp ( Celsius"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 } }
 ]
}